---
language: node_js
node_js:
  - stable
sudo: false
cache:
  directories:
    - node_modules
    - docs/site/node_modules
install:
  - npm install
  - cd docs/site && npm install
script:
  - ./scripts/run-travis-tests.sh
